# Generated by Django 4.2.16 on 2024-10-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wd2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
