# Generated by Django 5.1.2 on 2024-10-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wd2', '0002_remove_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_en_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
