# Generated by Django 5.1.2 on 2024-10-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wd2', '0003_alter_produit_marque_alter_produit_quantite_en_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
